### ISSUE TITLE
Multiple generations of a step in all classes in step class

### ISSUE THREAD

**Issue by ucollina82** [SpecFlowOSS/resharper-specflow#13]
If present other subclasses in step class one step are replicated in all sub classes

**Comment by Socolin** [comment]
Hello,

Can you test if this version of the plugin fix your problem:
 https://github.com/Socolin/resharper-specflow/actions/runs/541838666
- Download the artifact
- Extract the artifact
- Then install the plugin from the .zip in rider
![image](https://user-images.githubusercontent.com/539620/107103653-6dfa6000-67ec-11eb-9305-b5660fd22e22.png)

**Comment by Socolin** [comment]
I'm closing since I think this was fixed. Please repopen this issue with more details if you encounters this problem again
